---
author: LISA COES
---

# Estudio Cuantitativo

## Método

Se diseñó un cuestionario a partir de la revisión de literatura (Baker, 2016; Chin et al., 2021; Delikoura & Kouis, 2021; Enke et al., 2012; Gross & Ryan, 2015; Hail et al., 2020; Hodenu-wusu et al., 2020; Lacey et al., 2020; Ljubenkovic et al., 2021; López-Cardenas & Cubero-Castillo; 2021; Knudtson et al., 2019; Pardo Martínez & Poveda, 2018; Rodríguez, 2014; Rowley et al., 2017; Sturmer et al., 2017; Zhu, 2020 ), así como de los hallazgos de la etapa cualitativa.

El cuestionario consistió en 91 preguntas divididas en los siguientes módulos:

1) **Ciencia Abierta**: 18 ítems relativos al conocimiento y la valoración general de los investigadores hacia la Ciencia Abierta

2) **Diseño Transparente**: 20 ítems que abordan prácticas propias y percibidas en la comunidad sobre la transparencia en los diseños de investigación. Esto incluye tanto prácticas positivas (por ejemplo, *compartir códigos u otros materiales de investigación en un repositorio en línea de acceso público*) como negativas (por ejemplo, *creación post-hoc de hipótesis y explicaciones de datos*).

3) **Datos abiertos**: 19 ítems relativos a prácticas, conocimiento y valoración del acceso abierto a los datos de investigación.

4) **Investigación reproducible**: 15 ítems que indagan sobre conocimiento y valoración de la reproducibildiad de la investigación en Ciencias Sociales y la "crisis de reproducibilidad".

5) **Acceso abierto a publicaciones**: 14 ítems que tratan sobre conocimiento, prácticas y valoración de la publicación de artículos en revistas Open Access. 

El cuestionario fue aplicado mediante la plataforma FormR (Arslan et al., 2020; Arslan, 2025). FormR es un software de código abierto que permite diseñar cuestionarios complejos con un gran nivel de personalización. Al estar integrado con RStudio (R+ RMarkdown), facilita el trabajo colaborativo, independiente de la extensión del cuestionario. La plataforma permite la autoaplicación del cuestionario, ya se mediante una computadora o mediante teléfono celular. 

> Preguntar por muestreo

Se lograron 70 respuestas completas. La descripción de la muestra obtenida se describe a continuación

> Agregar tabla

Se realizó un análisis descriptivo uni y bivariado de los indicadores claves del cuestionario. El análisis se abocó a describir conocimientos, prácticas y valoraciones de los encuestados en torno a la ciencia abierta y los constructos descritos anteriormente. Estas variables fueron cruzadas por grupo etario, enfoque de investigación, etapa en la carrera académica, grado académico y género, con el fin de detectar posibles diferencias entre grupos. 


> Modelar o no modelar?

## Resultados

Conocimientos

Los niveles de familiaridad con conceptos relacionados a la ciencia abierta refrendan lo observado en las entrevistas cualitativas. Así, el concepto más reconocido por los encuestados es el de acceso abierto a publicaciones, en línea con lo descrito en la etapa anterior, donde la idea de apertura se encontraba relacionada predominantemente a los resultados y publicaciones de la investigación. En el otro extremo, sólo un 33% de los encuestados mencionan estar familiarizados con el pre-registro de hipótesis. En general, los niveles de conocimiento parecen ser mayores entre investigadores jóvenes y con enfoque predominantemente cuantitativo. 

Prácticas

En general, se observa una baja frecuencia de prácticas relacionadas con la ciencia abierta. Un 37% de los encuestados siempre o casi siempre utiliza repositorios en línea para subir información relacionada a sus investigaciones, y un 21% declara compartir códigos entre investigadores. Este tipo de prácticas son más comunes entre investigadores hombres, aquellos cuyo enfoque predominante es cuantitativo, y quienes están en una etapa inicial o intermedia de su carrera académica. 

Es interesante que, en general, los investigadores declaran mejores prácticas propias que las percibidas en la comunidad. De tal modo, sólo un 16% cree que siempre o casi siempre la comunidad utiliza repositorios en línea para subir información relacionada a sus investigaciones, y un 6% cree que los investigadores comparten códigos con esa frecuencia. 

Esta brecha es cierta también en lo relativo a las malas prácticas. Un 10% de los encuestados declara que casi siempre o siempre no informa estudios o variables que no alcanzaron significación estadística, mientras que un 51% percibe esta práctica como frecuente en la comunidad. Por otro lado, mientras un 6% declara reportar selectivamente resultados, el 47% cree que esto ocurre siempre o casi siempre entre la comunidad. Finalmente, mientras nadie reconoce manipular datos para validar una hipótesis, el 6% afirma que esto ocurre siempre o casi siempre en la comunidad. 

En general, la percepción de prácticas negativas en la comunidad es superior entre hombres que entre mujeres. Un 66% de los investigadores hombres cree que en la comunidad casi siempre o siempre no se informan resultados que no alcanzaron la significación estadística y un 59% cree que el reporte selectivo de resultado es una práctica frecuente en la comunidad. Esto puede estar relacionado a que los investigadores hombres, además, reconocen llevar a cabo estas prácticas con mayor frecuencia.

Por otro lado, se observa una alta percepción de barreras para el desarrollo de la ciencia abierta en todas sus dimensiones. La falta de políticas y la falta de incentivos son reconocidos como los principales factores que limitan a la ciencia abierta. En menor medida, pero también relevante, se reconoce la falta de conocimiento como una dificultad para el diseño transparente. La reticencia ante el plagio, además, es una de las principales razones que restringen la apertura de datos. 

Valoraciones

En general, se valora positivamente la posibilidad de adoptar medidas de Ciencia Abierta en las Ciencias Sociales. El acceso abierto (90%), la replicación de hallazgos (74%), el reporte de resultados no estadísticamente significativos (81%), y la disponibilización en línea de datos y materiales de análisis (81%), todas muestran un alto nivel de aceptación entre los encuestados. 

La única excepción es el pre-registro de hipótesis, que solo tiene un 49% de evaluación positiva. Esto se explica por un mayor nivel de desconocimiento (17% dice no conocer la medida), además de las reticencias observadas tanto en las entrevistas como en el apartado anterior. 

Salvo por el acceso abierto a publicaciones, la valoración positiva de estas medidas es mayor entre investigadores con enfoque cuantitativo (menor entre investigadores cualitativos e intermedio entre quienes practican enfoques mixtos), en la etapa inicial (hasta 5 años) o intermedia (de 6 a 15 años) de su carrera académica, y entre mujeres. 


Otros indicadores que se pueden agregar

Razones para abrir datos:
Generar redes (86%)
Mayor entre mujeres (93%) y entre investigadores cuantitativos (93%)
Difundir a la comunidad científica (79%)
Aumentar visibilidad (83%)
Mayro entre mujeres (90%) e investigadores cualitativos (89%)
Crisis de reproducibilidad
51% cree que hay una crisis importante de reproducibilidad, pero 31% no sabe si la hay. 
Entre los investigadores cuantitativos, el 82% cree que la crisis es importante. Entre los investigadores cualitativos el 59% no sabe si hay una crisis de reproducibilidad
El 59% cree que el 30% o menos de las investigaciones en ciencias sociales son reproducibles; El 83% cree que menos de la mitad de las investigaciones en ciencias sociales son reproducibles.
El 58% ha intentado reproducir sus propios resultados y el 43% los resultados de otros investigadores. Esta práctica es mayor entre investigadores cuantitativos y de carrera avanzada
El 51% de los intentos de reproducir resultados propios se han logrado reproducir completamente.
Solo el 19% de los intentos de reproducir resultados de otros investigadores han logrado una reproducción completa. Un 69% ha logrado reproducciones parciales.

