---
author: LISA COES
---

# Discussion

## Low knowledge, few practices

Both studies indicate a medium or low level of knowledge about the concepts of open science and an even lower lever of practices. The concept is mainly associated with the openness of results. Nevertheless, the qualitative study points out that it is not only understood as publication in open access journals, but also as other ways of engaging with the community and generating impact, understood beyond the metrics of academic journals.

This is also related to a series of practices aimed at openness and transparency of research results. Thus, in the qualitative study it was possible to observe accounts of experiences in open access publications, use of the "Gold Route" and sharing articles or pre-prints through social media or private platforms.

However, the level of knowledge and practices drops significantly for concepts and measures related to transparent design, openness of data, and transparency of analysis. In general, the quantitative study seems to distinguish that there are groups of researchers who show higher levels of knowledge and practices, particularly younger researchers and those whose predominant research approach is quantitative.

This lack of knowledge is recognized as one of the main barriers to implementing practices and policies that are consistent with open science principles. However, practices related to design transparency (such as pre-registration of hyphoteses), data openness (making data public or sharing them with other researchers), or analysis transparency (such as sharing analysis codes) encounter many more barriers and reluctance on the part of researchers, as discussed below.

## Positive general attitudes, particular concerns

As a general concept, open science is viewed positively. It is emphasized that its principles would allow better dissemination of results withing the scientific community, while avoiding malpractices. In addition, it would increase the possibility of generating impact beyond academic metrics, making it easier for communities and decision-makers to read the results. This is coupled with the awareness that public research funding implies a certain responsibility to make results and data available to academic and general public. Therefore, it is not surprising that 90% of the respondents are in favor of ANID implementing open access policies.

However, once certain practices are explored, concerns about the possibility and desirability of implementing open science measures related to transparency of designs, openness of data, and transparency of analysis begin to emerge. We identified three key issues:

First, the **difficulty of applying many of these measures in qualitative research**. With the exception of openness of results, the positive assessment of practices related to open science is higher among researchers with a quantitative approach and lower among those who practice predominantly qualitative approaches. This is line with what we observed in the first study, where it was noted that the preregistration and the openness of data generate important epistemological, methodological, and ethical conflicts with the traditional principles of qualitative research. Similarly, the replication crisis appears as a much greater concern among quantitative researchers, in line with what we observed in the first study, where reproducibility hardly appears on the horizon of qualitative researchers.

Second, the **difficulty of reconciling the principles of open science with the imperatives of academic productivity** imposes by universities and public funding agencies. Even the openness of results, the principle with the greatest legitimacy, must face the difficulty that ANID's funding structure favors publication in journals with payment barriers. On the other hand, measures such as pre-registration and open data raise suspicious about the protection of researcher's intellectual property and limit the originality and impact of potential publications.

Finally, we noted **a reluctance with regard to the motivations** behind the implementation of these measures. For some researchers, these practices do no escape the criticized logic of dissemination and funding. For example it is argued that sharing results and data brings personal benefits through increases of citations, in line with the demands of academic productivity.

In this sense, the quantitative study suggests that building networks and improving one's visibility are among the main motivations for opening data, especially among female researchers and those with intermediate academic career. Beyond any moral judgment about the motivations of those researchers, it would be interesting to investigate why there are specific groups that would be more inclined to adopt open sciences practices for extrinsic motivations.

## Critical assessment of ANID's policies

Both the qualitative and quantitative studies revealed a critical perception of ANID's open access policies. In particular, we observed a tension between the need for transparency and community impact of publicly funded research, and ANID's funding scheme --- which favors publication in journals that generally present payment barriers.

Researchers associate this with two problems. On the one hand, it is perceived as limiting the real possibility of research impact, distancing its results from communities and decision-makers. On the other hand, it is pointed out that this system results in the use of large amount of public funds to finance the business of large first-world scientific publishers.
