---
title: "Correlaciones parciales"
format: html
---

```{r}
#| labels: preparación
#| echo: false
#| include: false

library(formr)
library(tidyverse)
library(writexl)
library(sjlabelled)
library(summarytools)
library(sjmisc)
library(summarytools)
library(ggrepel)
library(gridExtra)
library(psych)
library(kableExtra)
library(corrplot)

remove(list = ls())
load("input/data/cais.RData")

lisa_v2_all <- cais %>% 
  rowwise() %>%
  mutate(n_NAs = sum(is.na(across(everything())))) #generamos una nueva variable que cuenta número de NA

lisa_v2_75 <- lisa_v2_all %>% 
  filter(n_NAs < 37)

cais_v2 <- lisa_v2_75 %>% 
  haven::zap_labels() %>% # eliminar las etiquetas de variables (haven_labelled) de una base de datos
  filter(mod01_6 > 1950) %>%  # filtrar datos de encuestas dudosas y de prueba
  mutate(edad0 = factor(car::recode(mod08_1, "28:34 = 1; 35:49 = 2; 50:80 = 3"), 
                        levels = c(1,2,3),
                        labels = c("28 a 34 años", "35 a 49 años", "50 o más años")),
         grado0 = factor(car::recode(mod01_5, "1=1; 2:3=2"),
                         levels= c(1,2),
                         labels= c("Magíster", "Doctorado")),
         etapa0 = factor(car::recode(mod01_1, "0:5 = 1; 6:15 = 2; 16:60 = 3"),
                         levels= c(1,2,3),
                         labels= c("Inicial (0 a 5 años)", "Intermedia (6 a 15 años)", "Avanzada (>15 años)")),
         enfoq0 = case_when(mod01_10 %in% c(1,2) ~ 0, 
                            mod01_10 %in% c(3,4) ~ 1,
                            mod01_10 == 4 ~ NA_real_),
         mod08_2= factor(mod08_2,
                         levels= c(1,2),
                         labels=c("Mujer", "Hombre")),
         sexo = as_label(mod08_2),
         edad = as_label(edad0),
         grado = as_label(grado0),
         etapa = as_label(etapa0),
         enfoq = as_label(enfoq0))



```

# Demográficos

```{r}
#| label: correlacion-demograficos

demo <- cais_v2 %>%
  dplyr::select(sexo, edad, grado, etapa, enfoq) %>%
  mutate(across(c(sexo, edad, grado, etapa, enfoq), ~as.numeric(.)))

m1 <- partial.r(demo, method = "pearson")
corrplot(m1, method="circle")

cor(demo$sexo, demo$enfoq, use= "complete.obs")

```
# Conocimiento

```{r}
#| label: correlacion-conocimientos

labels_cca <- c("ciencia_abierta", 
                "pubs_open_acces", 
                "prerregistro", 
                "apertura_datos", 
                "reproducibilidad", 
                "repos_abiertos", 
                "software_libre", 
                "datos_abiertos")

conocimiento <- cais_v2 %>%
  dplyr::select(mod02_1, starts_with("mod02_2"), sexo, edad, grado, etapa, enfoq) %>%
  mutate(
    across(c(sexo, edad, grado, etapa, enfoq), ~ as.numeric(.)),
    across(
      c(mod02_1, starts_with("mod02_2")),
      ~ (car::recode(., "1:3 = 1; 4:5 = 2; 6:7 = 3")))) %>%
  rename_with(~ labels_cca, .cols = c(mod02_1, starts_with("mod02_2")))


m2 <- partial.r(conocimiento)
corrplot(m2, method = 'circle')

```

# Prácticas

```{r}
#| label: correlaciones-prácticas-comunidad


labels_comu <- c("compartir_codigo",
                 "repos_abiertos",
                 "reportes_selectivos",
                 "no_reportar_p",
                 "manipular_dato")

practicas_comu <- cais_v2 %>%
  dplyr::select(starts_with("mod03_1_"), sexo, edad, grado, etapa, enfoq) %>%
  mutate(
    across(c(sexo, edad, grado, etapa, enfoq), ~ as.numeric(.)),
    across(
      c(starts_with("mod03_1_")),
      ~ (car::recode(., "1:2 = 1; 3 = 2; 4:5 = 3")))) %>%
  rename_with(~ labels_comu, .cols = c(starts_with("mod03_1_")))

m3 <- partial.r(practicas_comu)
corrplot(m3, method = 'circle')



```

```{r}
#| label: correlaciones-prácticas-propias

labels_prop <- c("compartir_codigos",
                 "utilizar_repos",
                 "reporte_selectivo",
                 "no informar_p")

practicas_prop <- cais_v2 %>%
  dplyr::select(starts_with("mod03_2_"), sexo, edad, grado, etapa, enfoq) %>%
  mutate(
    across(c(sexo, edad, grado, etapa, enfoq), ~ as.numeric(.)),
    across(
      c(starts_with("mod03_2_")),
      ~ (car::recode(., "1:2 = 1; 3 = 2; 4:5 = 3")))) %>%
  rename_with(~ labels_prop, .cols = c(starts_with("mod03_2_")))

m4 <- partial.r(practicas_prop)
corrplot(m4, method = 'circle')


```

# Valoraciones

```{r}
#| label: correlaciones-valoracoones

labels_valor <- c("Prerregistro", 
                  "disponibilizar_material", 
                  "reportar_no_significativo",
                  "Replicar",
                  "pubs_open_access")

valor <- cais_v2 %>%
  dplyr::select(starts_with("mod02_4_"), sexo, edad, grado, etapa, enfoq) %>%
  mutate(
    across(c(sexo, edad, grado, etapa, enfoq), ~ as.numeric(.)),
    across(
      c(starts_with("mod02_4_")),
      ~ (car::recode(., "1:2 = 1; 3 = 2; 4:5 = 3; 6 = 4")))) %>%
  rename_with(~ labels_valor, .cols = c(starts_with("mod02_4_")))

m4 <- partial.r(practicas_prop)
corrplot(m4, method = 'circle')

```


