---
author: LISA COES
project:
  output-dir: docs
---

# Introduction

Over the past few years, academia has experienced a number of challenges related to the concept of openness, which can be described in two main aspects. The first one refers to the so-called *replication crisis* [@baker_1500_2016; @nosek_promoting_2015; @peng_reproducibility_2015], referring to the difficulties in replicating research results due the lack of transparency in the research process, evidencing important variations in results in studies with identical data [@breznau_does_2021]. This has resulted not only in the failure to replicate many published findings, but also in the discovery and reporting of false data and results [@chopik_relationship_2020] in order to publishing in high impact journals.

The second main aspect comes from openness in terms of access, whereby several academic communities have reacted against the high payment barriers and the business model imposed by publishing houses to access the products of scientific research: universities pay a subscription to access the work even of their own researchers and the general public must pay again to obtains products funded by their taxes. One of the most commented reactions has been the cancellation of subscriptions to Elsevier's journals by prestige universities such as UCLA, which was subsequently resolved through an agreement based on the adoption and promotion of open-access practices.

Barriers to transparency and access are symptoms of an academic culture driven by the publication of indicators that are biased towards statistically significant results (p-hacking), leading to a tendency to force results, even going as far as manipulating and falsifying data to confirm proposed hypotheses [@head_extent_2015], establishing ad hoc hyphotesis after knowing the results of a study (HARKing) [@hollenbeck_harking_2017; @kerr_harking_1998]. As a result, the main audience for science is ultimately the editors of high-impact journals, while other audiences -- such as civil society, decision-makers and citizens --- are left out.

A growing number of initiatives around the world are addressing issues of reproducibility, transparency, and access in science, such as the Center for Open Science (COS), the Berkeley Initiative for Transparency in Social Sciences (BITSS), and the Teaching Integrity in Empirical Research (TIER) project. These initiatives promote openness at various stages of the research process, such as transparency of research designs through preregistration of studies, reproducibilty of analyses and data manipulation, and publication of preprints without paywalls. Many of these practices have been adopted by journals as recommendations or even requirements for publication, as well as promoted by governmental scientific institutions. All of this implies a major change in the way science is conceived, practiced, and taught. Moreover, it seems to be a necessary step to make science more relevant and closer to those outside of academia. In other words, it would be difficult to improve openness and exchange with local communities if the work within academia is mostly closed and non-collaborative.

Like many others developments in science, the open science movement has arrived slowly to Latin America, especially in social sciences. Although there have been some initiatives in recent years (such as the Open Science and Citizen Congress in Argentina 2018 or the OpenCon Latam in Colombia 2019), most of them are driven mainly by the natural sciences. In this line, Chile's National Agency for Research and Development (ANID) has implemented since 2021 and **Open Access Policy for scientific information and research data**, which aims to establish a standard of public access to research products that have been funded by ANID --- including social sciences projects. Therefore it is of strategic nature to develop initiatives that aim to contribute to the openness of sciences.

Based on this diagnosis, we aimed to identify the knowledge, attitudes and practices of open science among social science academics in Chile. From this analysis, we expect to generate debate and proposal for both academic work and science policies.
