---
author: LISA COES
---

# Qualitative Study

## Methods

We conducted a total of 13 semi-structured interviews with empirical social science researchers, who were selected through a simple random sampling method based on predetermined criteria. The sampling frame considered all academics who had been granted with a Regular Fondecyt (National Fund for Scientific and Technological Development) Project between 2018 and 2019 in the following study groups: Anthropology and Archaeology, Economic and Administrative Sciences, Legal and Political Sciences, Psychology, and Sociology.

To ensure a diverse sample, we allocated quotas based on sex and study group, randomly selecting one or two informants per sex for each study group. Researchers primarily engaged in theoretical research, those specializing in philosophical research within Legal and Political Science study group, those not dedicated to social anthropology within the Anthropology and Archaeology study group, and those focused on neuroscience within the Psychology study group, were excluded from the sample. Finally, given the multidisciplinary composition of the sociology study group --- which includes researchers from related fields, such as social psychology and social work --- we employed a randomization process to ensure the inclusion of at least one sociologist. The final composition of the sample is presented in @tbl-qual-sample

| Study Groups                                       | Men | Women |
|----------------------------------------------------|-----|-------|
| Anthropology and Archaeology (Social Anthropology) | 0   | 2     |
| Economic and Administrative Sciences (Economics)   | 1   | 1     |
| Legal and Political Sciences (Political Science)   | 2   | 1     |
| Psychology                                         | 1   | 2     |
| Sociology                                          | 1   | 2     |

: Qualitative Study Sample Description {#tbl-qual-sample}

Despite it was not considered as a sample inclusion criterion, the participants mirror the methodological diversity observed in the social sciences in Chile [@ramos_campo_2008]. Specifically, six researchers predominantly utilize qualitative methods, five predominantly work with quantitative methods, and two use mixed methods.

The interviews were conducted via video call, with a duration ranging from forty minutes to one hour. We addressed topics such as researchers' familiarity and knowledge about open science, their engagement in open science practice, their attitudes of openness and transparency practices, and the potential compulsory use of these practices in the future.

We employed a qualitative thematic analysis, as is a method that facilitates the identification and description of patterns of meanings [@braun_using_2006], as well as the set of relationships and hierarchies that are generated between them, organized around the concept of open science and the ideas associated with it, based on both semantic and latent codes [@boyatzis_transforming_2010]. In this sense, this method is particularly useful for understanding participants' views, knowledge, experiences, and values regarding open science.

Two research team members conducted primarily the analysis, with support from ATLAS.ti qualitative analysis software version 9.0.5. The coding process was carried out simultaneously by both researchers and discussed in regular team meetings. This approach ensured triangulation throughout the analysis process [@nowell_thematic_2017]. In addition, versions of the project and its products were systematically archived, and the researchers' personal reflection and team discussions about the analysis were recorded in a reflective diary, in order to safeguard the auditability of the research process [@lewins_using_2007].

Throughout the results report, we will reference specific participants in parentheses, indicating their discipline and their predominant methodological approach. For example, we will use tags such as *Sociology, mixed-methods* or *Economics, quantitative*.

# Results

### **Open Science: A fuzzy concept**

Initially, the concept of open science seems to be a difficult idea to define, seemingly distant to the participants. Most interviewees indicated that they were unfamiliar with the idea of open science and did not associate it with concrete practices or initiatives. However, this coexist with varying degrees of awareness of the problems faced, common practices of openness and transparency, and even experiences of researchers who have been directly involved in a number of institutional or international open science initiatives.

Rather than referring to concrete open science practices, the concept is mainly associated with a variety of research initiatives and policy orientations. It is strongly associated with community engagement or scientific dissemination, as well as with access of the general population or "communities" to research results.

Some interviewees also associate the concept with knowledge production, referring to the involvement of participants, communities and stakeholders in the research process; the use mixed (Sociology, qualitative); or interdisciplinary (Anthropology, qualitative; Sociology, qualitative) methods. Few refer to practices such as open data or publication in open access journals.

Despite the difficulties in defining it, we observed mostly positive attitudes about open science, at least in the first instance. These range from it direct association with democratic values and knowledge democratization, to more vague and doubtful assessments. However, some negative perceptions have also been observed, with some researchers referring to open science as a "fever" --- i.e. a passing trend --- or as an "overly ambitions project".

### **Open Science attitudes and practices**

#### a. Open Results

In the interviews, the idea of openness is fundamentally linked to the openness of results. There is a consensus to prioritize this practices, either through open access journals, policies such as the Gold Route (Pyshcology, quantitative; Anthropology; qualitative), or by sharing preprints and final versions in academic or personal social media.

Regarding the initiative of sharing and requesting articles or previous versions in academic social media, two main attitudes stand out among researchers. On the one hand, there is an attitude of suspicion towards this type of practices, considering it a mixture of altruism and personal interest (Psychology, quantitative). Although scientific collaboration is valued and desirable, it is recognized that it benefits the researcher by increasing the number of citations. This suspicion of an instrumental motivation, linked to funding policies, leads some researchers to refrain from these practices.

On the other hand, we found that the existence of non-dissemination clauses in many journals discourage the sharing of results, although no researcher reported being sanctioned or audited for sharing their publications. Beyond any concern, the high value placed on the openness of results encourage researchers to share their publications in academics social media or other platforms.

To facilitate access to the results of their projects, some researchers have resorted to legal means such as the Gold Route. This alternative allows free access to publications against payment by the authors. However, this option is viewed negatively by some respondents, who have expressed their refusal to pay for this service again in the future due recent increases in fees (Psychology, quantitative; Anthropology, qualitative).

In light of this, it is questioned whether these initiative truly reflect the principles of open science, criticizing the role and market power of large publishers. It is argued that these practices are based on shifting the cost of access from users to researchers (Psychology, quantitative). However, these views coexist with a more pragmatic perspective that recognize that, given the model is based on free peer preview and sale of access, someone must assume the cost of openness (Political Science, mixed-methods).

On the other hand, it is possible to identify a generally negative attitude towards ANID's dissemination policy, as it is perceived as inadequate for the dissemination of knowledge produced with public funds. Interviewees report the rigidity of the policy to the extent that it makes it difficult to carry out certain dissemination initiatives aimed at non-academic audiences, such as the publications of podcasts.

In addition, it is highlighted that ANID's funding structure places a greater emphasis in WoS and Scopus indexed journals, to detriment of Spanish-language OA journals. Although the latter have less academic impact, it is recognized that they are more accessible to the general public and decision-makers.

On the contrary, the prioritization of English-language paywalled journals is perceived as a "transfer of capital from the global South to the global North" (anthropology, qualitative). In this way, research funded with public resources is published in paywalled journals to which national researchers or their universities must pay --- usually with public funds --- in order to gain access.

Thus, interviewees identify tensions between the need to open and disseminate the results of publicly funded research, the rigidity of ANID's dissemination policy, and its funding and incentive scheme. In order to balance the pressure to publish in high-impact journals with the principles of openness, researchers have adopted strategies such as diversifying their research outputs. On of them is the "sacrifice of publications", which implies deferring results: some are sent to high impact journals in order to maximize scores in future funding applications; others are sent to local open journals in Spanish, which are more accessible to the general public. The following quote illustrates this practices and its effects:

::: callout
\[...\] we published in a journal which is... I think it is only SciELO \[...\] I have published much better things, let's say, in better journals than that one, and I have never been called by the Ministry \[...\] And for this article they called us, they asked us for an interview, just yesterday we had to make a presentation for all the teams working on the topic we are researching. So \[...\] it is necessary to make that effort to, sometimes, sacrifice, in quotation marks, some data and publish them in journals with lower indexation, because in the end those are the ones that are disseminated more and reach more where one... or at least where I would expect them to reach, which is where decisions can be made \[...\] (Psychology, quantitative)
:::

In line with the previous quote, is is noted that the idea of openness is not limited to access to academic publications, but that the results must have "social impact". With this in mind, practices such as the publications of columns and editorial in written press (Psychology, quantitative), the creation of documentaries (Sociology, qualitative), and instances of feedback with the communities that participated in the study (Anthropology, qualitative; Psychology, quantitative) are adopted.

Finally, with regard to access to scientific publications, the interviewees emphasized the role played by the universities where they work, specially through their libraries. For this reason, respondents indicated that they had not experienced difficulties in accessing publications. On the other hand, others recognize that in Latin America the practice of accessing scientific products such as preprints or working papers though informal mechanisms or even piracy is widespread among researchers and provides yet another mean of dealing with access problems without major consequences.

#### b. Design Transparency

Only a few respondents reported having pre-registered their research on the Open Science Framework website (Psychology, quantitative; Political Science, mixed-methods) or though journal initiatives (Political Science, mixed-methods; Economics, quantitative). In the case of economics, it is noted that pre-registration is a widespread practice given the protocols of the American Economics Association. These have been evaluated positively, but in some cases they are considered as an excessive standard due to its obligatory nature in many journals. All this experiences seem to point to the importance of editorial initiative in promoting transparency practices in the research process.

However, the vast majority of respondents were not really familiar with the concept of pre-registration. Another group of respondents were aware of the idea, but without practicing it, and outlined various arguments against it, such as:

-   The idea that pre-registration is only possible in certain types of research --- quantitative research with hypothesis --- so its practice does not make sense in other designs (Psychology, qualitative; Economics; quantitative).

-   It is argued that pre-registration can be a "straitjacket" (Political Science, qualitative), especially in the case of following a more inductive logic. For some researchers, the design exists only in its execution (Sociology, qualitative), so equivalence between an earlier design and the final product cannot be guaranteed.

-   There are concerns about intellectual property rights when publishing research designs that have not yet been carried out (Psychology, quantitative).

In sum, despite highlighting the fact that the pre-registration of hypotheses make it possible to ensure that a research does not involve practices such as HARKing, the low knowledge and training in this practice, its association with certain types of research, the methodological limitations raised, and the concerns related to intellectual property are the bases of the suspicion and consequent low extent of this practice.

#### c. Open Data

Positive attitudes towards open data are mainly based on the belief that it is useful for the development of science. This is because it is understood to enhance the scientific impact of publications associated with the data, to save human and financial resources allocated to data production, and to reduce the impact on marginalized communities or social groups that are more often studied.

Particularly in the case of publicly funded research, most researchers showed a very positive attitude towards data openness, and several pointed out that it should be a stronger or mandatory requirement. Some researchers even argued that data in this type of research are public goods, and non-availability of data was perceived as illegitimate hoarding.

On the other hand, some researchers question the obligation of data openness, highlighting the personal investment and additional cost involved. They argue that data are research property, at least temporarily, since their production requires innovation, creativity, and the building of relationship with subjects or institutions. For these researchers, data production is therefore an intellectual production, not a simple investment of public resources executed by the researcher.

In addition, there is a tension between open data and the pressure to publish, not only because of the time the researcher must devote to opening data, but also because of the pressure for scientific products with original and novel questions and designs. Thus some researchers question the value of open data, arguing that it is difficult to use public data in new ways because it has already been used.

Along with this suspicion about the usefulness of open data, we observed doubts about whether this practice is suited to the specificity of social science research. Thus, respondents pointed to the methodological costs and ethical risk that researchers perceive in practice, drawing a distinction between quantitative and qualitative research.

On the one hand, all researchers agreed that most quantitative data should not require special ethical protocols or conditions of use, except for data generated in special populations or in economics studies where the data belong to private companies.

On the other hand, the opening of qualitative data faces significant challenges from the perspective of respondents, such as protecting the identity of participants. It is mentioned that even if it were possible to mobilize human resources for data anonymization, the risk of harm to many communities exceed their anonymity. In addition, the decontextualization of the data due the loss of the relationship between the researcher and the communities limits the analysis and discourages its use.

It is noteworthy that despite the perceived differences in the ease and relevance of openness between qualitative and quantitative data, only two of the researchers interviewed --- one qualitative and one quantitative --- had ever practiced open data publication beyond editorial requirements and sharing data directly with other researchers.

#### d. Analysis Transparency

Analysis transparency is valued for its contribution to scientific progress and to the methodological learning of new researchers. In addition, a growing demand from high-impact journals for more detailed methodological sections in qualitative research and for the disclosure of analysis codes in quantitative studies is perceived and appreciated. This increased transparency is associated with greater analytical rigor and validity of results.

Practices and expectations of transparency differ between qualitative and quantitative research. In the former, transparency is mainly associated with methodological clarity in publications, occasionally supplemented by appendices detailing some procedures. However, publication of input such as codebooks or software outputs are not a priority for qualitative researchers, nor are expectation of reproducibility.

The transparency of quantitative analysis tends to be associated with the public or private availability of analysis codes developed. It is noteworthy that in many cases this availability tends to be requested by academic journals. Although it is not fully addressed, it is possible to conclude that the greater use of software for these procedures, compared to what happens in qualitative research, tends to facilitate the consolidation of a set of practices and attitudes more favorable to the transparency of analyses.

However, no researcher reported having openly published their analysis code, as these are usually shared privately, through academic networks or personal contacts. It is mentioned that the codes are like "toothbrushes" (Economics, quantitative), highly personal and not designed for public sharing. In addition, ethical and methodological complications, as well as the need for clarity and tidiness in the codes for them in order to be useful, highlight the lack of a standard for their publication. Finally, it is mentioned that in some disciplines, such as economics, researchers have not migrate to open source software due to the persistence of the widespread use of programs with payment barriers.
