---
author: LISA COES
---

# Conclusion

The studies presented here show that for the social science community in Chile, open science is fundamentally associated with open access to research results, whether through open access journals or other forms of dissemination. This is accompanied by a set of practices, a positive assessment of these measures, and critical positions towards the policies promoted by ANID. Nevertheless, other dimensions of open science (as transparent design, open data and transparency of analysis) show a lower level of knowledge, a lower frequency of practices and a ambivalent evaluation.

However, we observed some differences between groups of researchers, particularly with respect to research approach. For instance, researchers with a quantitative approach reported a higher level of knowledge, a greater number and frequency of practices, a greater concern about replication crisis, and a higher appreciation of the measures promoted by Open Science. Qualitative researchers, on the other hand, showed greater reluctance, ranging from practical barriers to epistemological concerns.

Age and gender appear to influence knowledge, practices and attitudes towards open science. Future research could aim to formulate models that explain difference in disposition towards open science, as well as distinguish between intrinsic and extrinsic motivations for accepting this types of measures.

Taken together, both studies raise important challenges for open social science in Chile. First, the need to review ANID's funding and dissemination policies in other to better meet both the needs of researchers and the principles of open science. Thus, the concerns raised by the participants regarding the use of public resources are of paramount importance and cannot be ignored.

Second, the studies highlight the need to bridge knowledge and incentive gaps in order to allow greater openness to the application of open sciences measures in all its dimensions. This implies opening spaces for methodological and epistemological debate to overcome the reluctance observed among some groups of researchers, particularly those with a predominantly qualitative approach.

# References
